server:
  port: 5555
  
spring:  application:    name: service-gateway
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
zuul:  ignored-services:  - baseservice
  prefix: /api  routes:    baseservice: /base/**
    legacyservice:
      path: /legacy/**
      service-id: legacyservice
      
legacyservice:
  ribbon:
    listOfServers:
      - localhost:10000
      - localhost:10001
      - localhost:10002
    